### ISSUE TITLE
Villaer Shop issue with menus along with galacticraft

### ISSUE THREAD

**Issue by mrdeadlocked** [DosMike/MegaMenus#3]
VShop created with villager popups menu but shows default villager style menu. SPonge:human shop does not open at all. Error is pastebined below

https://pastebin.com/n4t5tfUJ

forge-1.12.2-14.23.5.2822-universal.jar
spongeforge-1.12.2-2768-7.1.6-RC3616.jar

VillagerShops-2.0.jar
Mega Menus-0.3.jar

**Comment by DosMike** [comment]
Should be fixed with the next release
