### ISSUE TITLE
Interacting with "Drop key" causes items to disappear and triggers antiglitch

### ISSUE THREAD

**Issue by GlassSpirit** [DosMike/MegaMenus#8]
Create simple menu with few buttons, hower mouse over one, press Q or your "drop item" key.
The item just disappears with log in chat (if antiglitch disabled), or antiglitch system is triggered.
I think you should just cancell the ClickInventoryEvent.Drop event in this case.

**Comment by DosMike** [comment]
Interesting, when i cancel the ClickInventoryEvent.Drop in GuiRender#unlinkedInventoryProvider#instanceListener, i can cancel it if the player drops an item from their personal inventory, but the event does not seem to trigger for items dropped from the menu - not event event.getClass().getName() is logged... I'll have to play with that over the weekend
